CNPM/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPM.Models;
using PagedList;

namespace CNPM.Controllers
{
    public class SanPhamsController : Controller
    {
        private CNPMEntities db = new CNPMEntities();

        // GET: SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSP);
            return View(sanPhams.ToList());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.maloai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maloai,MaSP,TenSP,MoTa,GiaBan,Hinh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maloai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.maloai);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.maloai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.maloai);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maloai,MaSP,TenSP,MoTa,GiaBan,Hinh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maloai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.maloai);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Products
        public ActionResult SPList(string loaisp, string SearchString, int? page)
        {   // Tạo Products và có tham chiếu đến Category
            var sanphams = db.SanPhams.Include(p => p.LoaiSP);
            // Tìm kiếm chuỗi truy vấn theo category
            if (loaisp == null)
            {
                sanphams = db.SanPhams.OrderByDescending(x => x.TenSP);
            }
            else
            {
                sanphams = db.SanPhams.OrderByDescending(x => x.maloai).Where(x => x.maloai == loaisp);
            }


            //Tìm kiếm chuỗi truy vấn theo NamePro, nếu chuỗi truy vấn SearchString khác rỗng, null
            if (!String.IsNullOrEmpty(SearchString))
            {
                sanphams = sanphams.Where(s => s.TenSP.Contains(SearchString));
            }

            // Khai báo mỗi trang 4 sản phẩm
            int pageSize = 12;
            // Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // Nếu page = null thì đặt lại page là 1.
            if (page == null) page = 1;

            // Trả về các product được phân trang theo kích thước và số trang.
            return View(model: sanphams.ToPagedList(pageNumber, pageSize));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CNPM/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CNPM.Models;

namespace CNPM.Controllers
{
    public class ShoppingCartController : Controller
    {
        CNPMEntities db = new CNPMEntities();
        // GET: ShoppingCart, chuẩn bị dữ liệu cho View
        public ActionResult ShowCart()
        {
            if (Session["Cart"] == null)
                return View("ShowCart");
            Cart _cart = Session["Cart"] as Cart;
            return View(_cart);
        }
        // Tạo mới giỏ hàng, nguồn được lấy từ Session
        public Cart GetCart()
        {
            Cart cart = Session["Cart"] as Cart;
            if (cart == null || Session["Cart"] == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
        // Thêm sản phẩm vào giỏ hàng
        public ActionResult AddToCart(string id)
        {
            // lấy sản phẩm theo id
            var _pro = db.SanPhams.SingleOrDefault(s => s.MaSP == id);
            if (_pro != null)
            {
                GetCart().Add_Product_Cart(_pro);
            }
            return RedirectToAction("ShowCart", "ShoppingCart");
        }
        // Cập nhật số lượng và tính lại tổng tiền
        public ActionResult Update_Cart_Quantity(FormCollection form)
        {
            Cart cart = Session["Cart"] as Cart;
            string id_pro = Request.Form["idPro"];
            int _quantity = int.Parse(Request.Form["carQuantity"]);
            cart.Update_quantity(id_pro, _quantity);

            return RedirectToAction("ShowCart", "ShoppingCart");
        }
        // Xóa dòng sản phẩm trong giỏ hàng
        public ActionResult RemoveCart(string id)
        {
            Cart cart = Session["Cart"] as Cart;
            cart.Remove_CartItem(id);

            return RedirectToAction("ShowCart", "ShoppingCart");
        }

        // Các phương thức cho thanh toán
        public ActionResult CheckOut(FormCollection form)
        {
            try
            {
                Cart cart = Session["Cart"] as Cart;
                HoaDon _order = new HoaDon();
                _order.NgayDat = DateTime.Now;
                _order.DiaChiGiao = form["AddressDeliverry"];
                _order.makh = int.Parse(form["CodeCustomer"]);
                db.HoaDons.Add(_order);
                foreach (var item in cart.Items)
                {
                    // lưu dòng sản phẩm vào chi tiết hóa đơn
                    CTHD _order_detail = new CTHD();
                    _order_detail.mahd = _order.MaHD;
                    _order_detail.masp = item._product.MaSP;
                    _order_detail.DonGia = (double)item._product.GiaBan;
                    _order_detail.SoLuong = item._quantity;
                    db.CTHDs.Add(_order_detail);
                }
                db.SaveChanges();
                cart.ClearCart();
                return RedirectToAction("CheckOut_Success", "ShoppingCart");
            }
            catch
            {
                return Content("Có sai sót! Xin kiểm tra lại thông tin"); ;
            }
        }

        // Thông báo thanh toán thành công
        public ActionResult CheckOut_Success()
        {
            return View();
        }

        // Thông báo thanh toán thành công
        public ActionResult ThanhToan()
        {
            return View();
        }

    }
}

CNPM/Views/ShoppingCart/CheckOut_Success.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<h2>Thanh toán thành công</h2>
<h2>Hẹn gặp lại quí khách</h2>

CNPM/Views/ShoppingCart/ShowCart.cshtml
@model CNPM.Models.Cart

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<a href="@Url.Action("SPList", "SanPhams")" class="btn btn-default"> Tiếp tục Mua hàng</a>
@if (Model != null)
{
    <table class="table-bordered">
        <thead style="text-align:center; font-size:large;">
            <tr>
                <th>Tên Sản phẩm</th>
                <th>Hình</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                decimal total = item._quantity * (decimal)item._product.GiaBan;
                <tr>
                    <td width="400">@Html.DisplayFor(model => item._product.TenSP)</td>
                    <td><img src="~/Content/images/@item._product.Hinh" width="100" height="110" /></td>
                    <td width="100" align="right"> @String.Format("{0:.000}", @item._product.GiaBan)</td>
                    <td align="right">
                        @using (Html.BeginForm("Update_Cart_Quantity", "ShoppingCart"))
                        {
                            <input type="hidden" value="@item._product.MaSP" name="idPro" />
                            <input type="number" value="@item._quantity" name="carQuantity" style="text-align:right" />
                            <input type="submit" value="Cập nhật" />
                        }
                    </td>
                    <td width="100" align="right">@total.ToString("#.##0").Replace(',', '.')</td>
                    <td>
                        <a href="RemoveCart/@item._product.MaSP" class="btn-danger">- Xóa -</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <a href="@Url.Action("ThanhToan", "ShoppingCart")" class="btn btn-danger"> Thanh toán</a>
        </tfoot>
    </table>
}
else
{
    <span class="alert alert-danger"> Giỏ hàng rỗng ! Xin mời tiếp tục mua hàng</span>
}

CNPM/Views/ShoppingCart/ThanhToan.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<body>
    <div>
        @Html.ActionLink("Quay lại giỏ hàng", "ShowCart")
    </div>
    <br />
    <table class="table-bordered" style="width:1111px;">
        <tr>
            <th style="padding:10px">Địa chỉ giao hàng</th>
        </tr>
        <tr>

            <td style="padding-left:10px">
                <br />
                <div style="display:flex;">
                    Họ tên&emsp;&ensp;&emsp;&emsp;
                    <input name="shipment_name" type="text" class="form-control control-width-normal" maxlength="50" value="">
                </div><br />
                <div style="display:flex;">
                    Email&emsp;&emsp;&emsp;&emsp;
                    <input name="email" type="text" autocorrect="off" autocapitalize="none" class="form-control control-width-normal" maxlength="50" value="">
                </div><br />
                <div style="display:flex;">
                    Điện thoại&emsp;&emsp;
                    <input id="shipment-phone" name="shipment_phone" type="text" class="form-control control-width-normal" maxlength="30" value="">
                </div><br />
            </td>

            <td style="padding-left:10px">
                <br />
                <div style="display:flex;">
                    Địa chỉ&emsp;&ensp;&emsp;&emsp;
                    <input name="shipment_address" type="text" class="form-control control-width-normal" value="">
                </div><br />
                <div style="display:flex;">
                    Tỉnh/Thành&emsp;&ensp;
                    <select name="calc_shipping_provinces" required="">
                        <option value="">Tỉnh / Thành phố</option>
                    </select>
                </div><br />
                <div style="display:flex;">
                    Quận/Huyện&emsp;
                    <select name="calc_shipping_district" required="">
                        <option value="">Quận / Huyện</option>
                    </select>
                </div><br />
                <div style="display:flex;">
                    Phường/Xã&emsp;&ensp;
                    <select name="calc_shipping_ward" required="">
                        <option value="">Phường / Xã</option>
                    </select>
                </div><br />
            </td>
        </tr>
    </table>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
    <script src='https://cdn.jsdelivr.net/gh/vietblogdao/js/districts.min.js'></script>
    <script>
    //<![CDATA[
        if (address_2 = localStorage.getItem('address_2_saved')) {
            $('select[name="calc_shipping_district"] option').each(function () {
                if ($(this).text() == address_2) {
                    $(this).attr('selected', '')
                }
            })
            $('input.billing_address_2').attr('value', address_2)
        }
        if (district = localStorage.getItem('district')) {
            $('select[name="calc_shipping_district"]').html(district)
            $('select[name="calc_shipping_district"]').on('change', function () {
                var target = $(this).children('option:selected')
                target.attr('selected', '')
                $('select[name="calc_shipping_district"] option').not(target).removeAttr('selected')
                address_2 = target.text()
                $('input.billing_address_2').attr('value', address_2)
                district = $('select[name="calc_shipping_district"]').html()
                localStorage.setItem('district', district)
                localStorage.setItem('address_2_saved', address_2)
            })
        }
        $('select[name="calc_shipping_provinces"]').each(function () {
            var $this = $(this),
                stc = ''
            c.forEach(function (i, e) {
                e += +1
                stc += '<option value=' + e + '>' + i + '</option>'
                $this.html('<option value="">Tỉnh / Thành phố</option>' + stc)
                if (address_1 = localStorage.getItem('address_1_saved')) {
                    $('select[name="calc_shipping_provinces"] option').each(function () {
                        if ($(this).text() == address_1) {
                            $(this).attr('selected', '')
                        }
                    })
                    $('input.billing_address_1').attr('value', address_1)
                }
                $this.on('change', function (i) {
                    i = $this.children('option:selected').index() - 1
                    var str = '',
                        r = $this.val()
                    if (r != '') {
                        arr[i].forEach(function (el) {
                            str += '<option value="' + el + '">' + el + '</option>'
                            $('select[name="calc_shipping_district"]').html('<option value="">Quận / Huyện</option>' + str)
                        })
                        var address_1 = $this.children('option:selected').text()
                        var district = $('select[name="calc_shipping_district"]').html()
                        localStorage.setItem('address_1_saved', address_1)
                        localStorage.setItem('district', district)
                        $('select[name="calc_shipping_district"]').on('change', function () {
                            var target = $(this).children('option:selected')
                            target.attr('selected', '')
                            $('select[name="calc_shipping_district"] option').not(target).removeAttr('selected')
                            var address_2 = target.text()
                            $('input.billing_address_2').attr('value', address_2)
                            district = $('select[name="calc_shipping_district"]').html()
                            localStorage.setItem('district', district)
                            localStorage.setItem('address_2_saved', address_2)
                        })
                    } else {
                        $('select[name="calc_shipping_district"]').html('<option value="">Quận / Huyện</option>')
                        district = $('select[name="calc_shipping_district"]').html()
                        localStorage.setItem('district', district)
                        localStorage.removeItem('address_1_saved', address_1)
                    }
                })
            })
        })
//]]></script>
</body>
<br />
<a href="@Url.Action("CheckOut_Success", "ShoppingCart")" class="btn btn-danger" style="float:right"> Thanh toán</a>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}