CNPM/Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string tentk { get; set; }
        public string mk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}

CNPM/Controllers/KhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPM.Models;

namespace CNPM.Controllers
{
    public class KhachHangsController : Controller
    {
        private CNPMEntities db = new CNPMEntities();

        // GET: KhachHangs
        public ActionResult Index()
        {
            return View(db.KhachHangs.ToList());
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,TenKH,SDT,Email,DiaChi,tentk,mk")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,TenKH,SDT,Email,DiaChi,tentk,mk")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        // Tạo view cho khách hàng Login
        public ActionResult LoginCus()
        {
            return View();
        }
        // Xử lý tìm kiếm UserName, password trong Customer và thông báo
        [HttpPost]
        public ActionResult LoginAcountCus(KhachHang _cus)
        {
            // check là khách hàng cần tìm
            var check = db.KhachHangs.Where(s => s.tentk == _cus.tentk && s.mk == _cus.mk).FirstOrDefault();
            if (check == null)  //không có KH
            {
                ViewBag.ErrorInfo = "Không có KH này";
                return View("LoginCus");
            }
            else
            {   // Có tồn tại KH -> chuẩn bị dữ liệu đưa về lại ShowCart.cshtml
                db.Configuration.ValidateOnSaveEnabled = false;
                Session["MaKH"] = check.MaKH;
                Session["mk"] = check.mk;
                Session["TenKH"] = check.TenKH;
                Session["SDT"] = check.SDT;
                // Quay lại trang giỏ hàng với thông tin cần thiết
                return RedirectToAction("ShowCart", "ShoppingCart");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CNPM/Views/KhachHangs/Create.cshtml
@model CNPM.Models.KhachHang

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>THÊM KHÁCH HÀNG</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Tên khách hàng</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Số điện thoại</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Email</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Địa chỉ</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CNPM/Views/KhachHangs/Delete.cshtml
@model CNPM.Models.KhachHang

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script>
        function Xoa() {
            confirm("BẠN CÓ CHẮC MUỐN XOÁ KHÁCH HÀNG NÀY?");
        }
    </script>
</head>


<h1>XOÁ KHÁCH HÀNG</h1>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKH)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" onclick="Xoa();" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CNPM/Views/KhachHangs/Details.cshtml
@model CNPM.Models.KhachHang

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>KHÁCH HÀNG</h1>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKH)
        </dd>

        <dt>
            Tên khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKH)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CNPM/Views/KhachHangs/Edit.cshtml
@model CNPM.Models.KhachHang

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CẬP NHẬT KHÁCH HÀNG</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Tên khách hàng</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Số điện thoại</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Email</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Địa chỉ</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CNPM/Views/KhachHangs/Index.cshtml
@model IEnumerable<CNPM.Models.KhachHang>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h1>KHÁCH HÀNG</h1>

<p>
    @Html.ActionLink("Thêm khách hàng mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên khách hàng
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Email
        </th>
        <th>
            Địa chỉ
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaKH }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaKH }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.MaKH })
            </td>
        </tr>
    }

</table>

CNPM/Views/KhachHangs/LoginCus.cshtml
@model CNPM.Models.KhachHang

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>ĐĂNG NHẬP</h2>
<hr />
@using (Html.BeginForm("LoginAcountCus", "KhachHangs"))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@Session["chon"]" name="chon" />
    <table>
        <tr>
            <td style="padding: 5px">Tên đăng nhập</td>
            <td>@Html.TextBoxFor(model => model.tentk, new { style = "filed-validation-error" })</td>
            <td>@Html.ValidationMessageFor(model => model.tentk)</td>
        </tr>
        <tr>
            <td style="padding: 5px">@Html.LabelFor(model => model.mk)</td>
            <td>@Html.EditorFor(model => model.mk)</td>
            <td>@Html.ValidationMessageFor(model => model.mk)</td>
            @if (ViewBag.ErrorInfo == null)
            {
                <p>@ViewBag.ErrorInfo</p>
            }
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Login" class="btn btn-primary" /></td>
        </tr>
    </table>
}